### ISSUE TITLE
Does Beluganos use LXD's LXC or the older non-LXD LXC?

### ISSUE THREAD

**Issue by bmullan** [beluganos/beluganos#3]
i couldn't tell which Beluganos uses.

I use LXD and if Beluganos does also I would try it out.

The link:
Beluganos has one or more [Linux containers](https://linuxcontainers.org/)

Just takes  you to the Top of the [linuxcontainers.org](https://linuxcontainers.org/) website and from there you could goto the older LXC or goto the newer LXD/LXC?

thanks for any info
brian

**Comment by t-hirasawa1** [comment]
Beluganos uses LXC 3.0.3 as a VRF now and it is supported to be controlled by LXD.
So you may be able to control container by LXD.

Thanks
